//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleMan.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int InvoiceId { get; set; }
        public string Number { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Details { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
